models/jinx/w_grenadeT.mdl
maps/ahl_museum.res
maps/ahl_museum.txt
maps/ahl_museum_detail.txt
gfx/env/city_daybk.tga
gfx/env/city_daydn.tga
gfx/env/city_dayft.tga
gfx/env/city_daylf.tga
gfx/env/city_dayrt.tga
gfx/env/city_dayup.tga
gfx/detail/pshopd_01.tga
gfx/detail/pshopd_09.tga
gfx/detail/pshopd_10.tga
